#request a mission
# The first point defines the touchdown location.
# The second point defines the touchdown heading (along a course from the first to the second point).
NED_list landing_waypoints 

---
#response is a list of points in a NED_list
NED_list planned_waypoints
